[versions]
agp = "8.13.2"
kotlin = "2.3.0"
room = "2.8.4"
aboutLibraries = '13.2.1'
compose = '1.13.0'
compose110 = '1.10.0'
hilt = "2.57.2"
hilt-navigation = "1.3.0"
datastore-preferences = "1.2.0"
appcompat = "1.7.1"
lifecycle-runtime = "2.10.0"
core-ktx = "1.17.0"
activity-compose = "1.12.2"
material3 = "1.4.0"
materialIconExtended = "1.7.8"
ksp = "2.3.0"
compose-destinations = "2.3.0"
serialization-json = "1.9.0"
documentFile = "1.1.0"
workRuntimeKtx = "2.11.0"
startupRuntime = "1.2.0"
hilt-work = "1.3.0"
hilt-common = "1.3.0"
materialKolor = "4.0.5"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
graphicsShape = "1.1.0"
composeMarkdown = "0.5.8"
playServicesAds = "24.9.0"
splashScreen = "1.2.0"

[libraries]
# Android App
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose"}
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx"}
documentFile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentFile"}
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime"}
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime"}

# Compose
ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose110" }
ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "compose110" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose110" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose110" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose110" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose110" }
material = { group = "com.google.android.material", name = "material", version.ref = "compose" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref="materialIconExtended"}
graphics-shape = { group = "androidx.graphics", name = "graphics-shapes", version.ref = "graphicsShape" }
compose-destinations = { group = "io.github.raamcosta.compose-destinations", name = "core", version.ref = "compose-destinations" }
compose-destinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "compose-destinations" }

# Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }

# DI Hilt
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }
hilt-viewmodel-compose = { group = "androidx.hilt", name = "hilt-lifecycle-viewmodel-compose", version.ref = "hilt-navigation" }
hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hilt-common" }
hilt-common-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-common" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-work" }

# Database
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# DataStore
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }

# Network

# WorkManager
workRuntimeKtx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }

# App Startup
startupRuntime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startupRuntime" }

# Kotlin
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization-json" }

# Other
aboutLibraries = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
composeMarkdown = { group = "com.github.jeziellago", name = "compose-markdown", version.ref = "composeMarkdown"}
materialKolor = { group = "com.materialkolor", name = "material-kolor", version.ref = "materialKolor" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "playServicesAds" }
splash-screen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
